name: Quality Gates

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  # Bun version
  BUN_VERSION: '1.3.0'

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ env.BUN_VERSION }}

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Type checking
      run: bunx turbo typecheck

    - name: ESLint checking
      run: bunx turbo lint

    - name: Prettier formatting check
      run: bun run format:check

    - name: Run tests
      run: bunx turbo test --filter='*[!e2e]*'

    - name: Security audit
      run: bun audit

    - name: Check bundle size
      run: bun run build

  mutation-testing:
    runs-on: ubuntu-latest
    needs: quality-checks
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ env.BUN_VERSION }}

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Run mutation testing
      run: bunx turbo test:mutation

    - name: Upload mutation report
      uses: actions/upload-artifact@v3
      with:
        name: mutation-report
        path: reports/mutation/

  performance-tests:
    runs-on: ubuntu-latest
    needs: quality-checks

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ env.BUN_VERSION }}

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Build packages
      run: bunx turbo build

    - name: Run performance benchmarks
      run: bunx turbo test:performance

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: performance/

  
  notify:
    runs-on: ubuntu-latest
    needs: [quality-checks, mutation-testing, performance-tests]
    if: needs.quality-checks.result == 'success'

    steps:
    - name: Notify quality status
      uses: actions/github-script@v6
      with:
        script: |
          const status = needs.quality-checks.result === 'success' ?
                       '✅ PASSED' : '❌ FAILED';

          console.log(`## Quality Gates Status: ${status}`);

          if (needs.quality-checks.result !== 'success') {
            core.setFailed('Quality gates failed');
          }